name: check

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.3                # Ubuntu Focal
          - 27.1                # Ubuntu Jammy
          - 28.2                # Debian Stable
          - 29.3                # Ubuntu Noble
          - 29.4
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: cider-storm.el
        ignore_warnings: ${{ matrix.ignore_warnings }}
    # - uses: leotaku/elisp-check@master
    #   with:
    #     file: cider-storm-stepper.el
    #     ignore_warnings: ${{ matrix.ignore_warnings }}
